# Permalinks
permalink: pretty

# Compile CSS
sass:
  style: compressed
sass:
  sass_dir: _sass

# Setup
title:            Asana Design
tagline:          'Asana has a bold, audacious mission: we want to make teamwork effortless, smart, and beautiful for every team. Our design team of brand, and product designers are at the heart of that mission.'
